ALTER TABLE Users ADD COLUMN IF NOT EXISTS username VARCHAR(50) UNIQUE;
ALTER TABLE Users ADD COLUMN IF NOT EXISTS passwordHash VARCHAR(255);
ALTER TABLE Users ADD COLUMN IF NOT EXISTS salt VARCHAR(255);
ALTER TABLE Users ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'user';
ALTER TABLE Users ADD COLUMN IF NOT EXISTS email VARCHAR(100);

ALTER TABLE Users ALTER COLUMN pass DROP NOT NULL;

ALTER TABLE Users ALTER COLUMN fName DROP NOT NULL;
ALTER TABLE Users ALTER COLUMN lName DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_users_username ON Users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON Users(email);
